# Generated by Django 4.2.2 on 2023-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
